// Generated by gencpp from file localizer_dwm1001/Anchor_2.msg
// DO NOT EDIT!


#ifndef LOCALIZER_DWM1001_MESSAGE_ANCHOR_2_H
#define LOCALIZER_DWM1001_MESSAGE_ANCHOR_2_H

#include <ros/service_traits.h>


#include <localizer_dwm1001/Anchor_2Request.h>
#include <localizer_dwm1001/Anchor_2Response.h>


namespace localizer_dwm1001
{

struct Anchor_2
{

typedef Anchor_2Request Request;
typedef Anchor_2Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Anchor_2
} // namespace localizer_dwm1001


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::localizer_dwm1001::Anchor_2 > {
  static const char* value()
  {
    return "4a842b65f413084dc2b10fb484ea7f17";
  }

  static const char* value(const ::localizer_dwm1001::Anchor_2&) { return value(); }
};

template<>
struct DataType< ::localizer_dwm1001::Anchor_2 > {
  static const char* value()
  {
    return "localizer_dwm1001/Anchor_2";
  }

  static const char* value(const ::localizer_dwm1001::Anchor_2&) { return value(); }
};


// service_traits::MD5Sum< ::localizer_dwm1001::Anchor_2Request> should match
// service_traits::MD5Sum< ::localizer_dwm1001::Anchor_2 >
template<>
struct MD5Sum< ::localizer_dwm1001::Anchor_2Request>
{
  static const char* value()
  {
    return MD5Sum< ::localizer_dwm1001::Anchor_2 >::value();
  }
  static const char* value(const ::localizer_dwm1001::Anchor_2Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::localizer_dwm1001::Anchor_2Request> should match
// service_traits::DataType< ::localizer_dwm1001::Anchor_2 >
template<>
struct DataType< ::localizer_dwm1001::Anchor_2Request>
{
  static const char* value()
  {
    return DataType< ::localizer_dwm1001::Anchor_2 >::value();
  }
  static const char* value(const ::localizer_dwm1001::Anchor_2Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::localizer_dwm1001::Anchor_2Response> should match
// service_traits::MD5Sum< ::localizer_dwm1001::Anchor_2 >
template<>
struct MD5Sum< ::localizer_dwm1001::Anchor_2Response>
{
  static const char* value()
  {
    return MD5Sum< ::localizer_dwm1001::Anchor_2 >::value();
  }
  static const char* value(const ::localizer_dwm1001::Anchor_2Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::localizer_dwm1001::Anchor_2Response> should match
// service_traits::DataType< ::localizer_dwm1001::Anchor_2 >
template<>
struct DataType< ::localizer_dwm1001::Anchor_2Response>
{
  static const char* value()
  {
    return DataType< ::localizer_dwm1001::Anchor_2 >::value();
  }
  static const char* value(const ::localizer_dwm1001::Anchor_2Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LOCALIZER_DWM1001_MESSAGE_ANCHOR_2_H
