// Generated by gencpp from file localizer_dwm1001/Anchor_3.msg
// DO NOT EDIT!


#ifndef LOCALIZER_DWM1001_MESSAGE_ANCHOR_3_H
#define LOCALIZER_DWM1001_MESSAGE_ANCHOR_3_H

#include <ros/service_traits.h>


#include <localizer_dwm1001/Anchor_3Request.h>
#include <localizer_dwm1001/Anchor_3Response.h>


namespace localizer_dwm1001
{

struct Anchor_3
{

typedef Anchor_3Request Request;
typedef Anchor_3Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Anchor_3
} // namespace localizer_dwm1001


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::localizer_dwm1001::Anchor_3 > {
  static const char* value()
  {
    return "4a842b65f413084dc2b10fb484ea7f17";
  }

  static const char* value(const ::localizer_dwm1001::Anchor_3&) { return value(); }
};

template<>
struct DataType< ::localizer_dwm1001::Anchor_3 > {
  static const char* value()
  {
    return "localizer_dwm1001/Anchor_3";
  }

  static const char* value(const ::localizer_dwm1001::Anchor_3&) { return value(); }
};


// service_traits::MD5Sum< ::localizer_dwm1001::Anchor_3Request> should match
// service_traits::MD5Sum< ::localizer_dwm1001::Anchor_3 >
template<>
struct MD5Sum< ::localizer_dwm1001::Anchor_3Request>
{
  static const char* value()
  {
    return MD5Sum< ::localizer_dwm1001::Anchor_3 >::value();
  }
  static const char* value(const ::localizer_dwm1001::Anchor_3Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::localizer_dwm1001::Anchor_3Request> should match
// service_traits::DataType< ::localizer_dwm1001::Anchor_3 >
template<>
struct DataType< ::localizer_dwm1001::Anchor_3Request>
{
  static const char* value()
  {
    return DataType< ::localizer_dwm1001::Anchor_3 >::value();
  }
  static const char* value(const ::localizer_dwm1001::Anchor_3Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::localizer_dwm1001::Anchor_3Response> should match
// service_traits::MD5Sum< ::localizer_dwm1001::Anchor_3 >
template<>
struct MD5Sum< ::localizer_dwm1001::Anchor_3Response>
{
  static const char* value()
  {
    return MD5Sum< ::localizer_dwm1001::Anchor_3 >::value();
  }
  static const char* value(const ::localizer_dwm1001::Anchor_3Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::localizer_dwm1001::Anchor_3Response> should match
// service_traits::DataType< ::localizer_dwm1001::Anchor_3 >
template<>
struct DataType< ::localizer_dwm1001::Anchor_3Response>
{
  static const char* value()
  {
    return DataType< ::localizer_dwm1001::Anchor_3 >::value();
  }
  static const char* value(const ::localizer_dwm1001::Anchor_3Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LOCALIZER_DWM1001_MESSAGE_ANCHOR_3_H
