// Generated by gencpp from file localizer_dwm1001/Anchor_1.msg
// DO NOT EDIT!


#ifndef LOCALIZER_DWM1001_MESSAGE_ANCHOR_1_H
#define LOCALIZER_DWM1001_MESSAGE_ANCHOR_1_H

#include <ros/service_traits.h>


#include <localizer_dwm1001/Anchor_1Request.h>
#include <localizer_dwm1001/Anchor_1Response.h>


namespace localizer_dwm1001
{

struct Anchor_1
{

typedef Anchor_1Request Request;
typedef Anchor_1Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Anchor_1
} // namespace localizer_dwm1001


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::localizer_dwm1001::Anchor_1 > {
  static const char* value()
  {
    return "4a842b65f413084dc2b10fb484ea7f17";
  }

  static const char* value(const ::localizer_dwm1001::Anchor_1&) { return value(); }
};

template<>
struct DataType< ::localizer_dwm1001::Anchor_1 > {
  static const char* value()
  {
    return "localizer_dwm1001/Anchor_1";
  }

  static const char* value(const ::localizer_dwm1001::Anchor_1&) { return value(); }
};


// service_traits::MD5Sum< ::localizer_dwm1001::Anchor_1Request> should match
// service_traits::MD5Sum< ::localizer_dwm1001::Anchor_1 >
template<>
struct MD5Sum< ::localizer_dwm1001::Anchor_1Request>
{
  static const char* value()
  {
    return MD5Sum< ::localizer_dwm1001::Anchor_1 >::value();
  }
  static const char* value(const ::localizer_dwm1001::Anchor_1Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::localizer_dwm1001::Anchor_1Request> should match
// service_traits::DataType< ::localizer_dwm1001::Anchor_1 >
template<>
struct DataType< ::localizer_dwm1001::Anchor_1Request>
{
  static const char* value()
  {
    return DataType< ::localizer_dwm1001::Anchor_1 >::value();
  }
  static const char* value(const ::localizer_dwm1001::Anchor_1Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::localizer_dwm1001::Anchor_1Response> should match
// service_traits::MD5Sum< ::localizer_dwm1001::Anchor_1 >
template<>
struct MD5Sum< ::localizer_dwm1001::Anchor_1Response>
{
  static const char* value()
  {
    return MD5Sum< ::localizer_dwm1001::Anchor_1 >::value();
  }
  static const char* value(const ::localizer_dwm1001::Anchor_1Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::localizer_dwm1001::Anchor_1Response> should match
// service_traits::DataType< ::localizer_dwm1001::Anchor_1 >
template<>
struct DataType< ::localizer_dwm1001::Anchor_1Response>
{
  static const char* value()
  {
    return DataType< ::localizer_dwm1001::Anchor_1 >::value();
  }
  static const char* value(const ::localizer_dwm1001::Anchor_1Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LOCALIZER_DWM1001_MESSAGE_ANCHOR_1_H
