// Generated by gencpp from file localizer_dwm1001/Tag_srvRequest.msg
// DO NOT EDIT!


#ifndef LOCALIZER_DWM1001_MESSAGE_TAG_SRVREQUEST_H
#define LOCALIZER_DWM1001_MESSAGE_TAG_SRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace localizer_dwm1001
{
template <class ContainerAllocator>
struct Tag_srvRequest_
{
  typedef Tag_srvRequest_<ContainerAllocator> Type;

  Tag_srvRequest_()
    {
    }
  Tag_srvRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::localizer_dwm1001::Tag_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::localizer_dwm1001::Tag_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Tag_srvRequest_

typedef ::localizer_dwm1001::Tag_srvRequest_<std::allocator<void> > Tag_srvRequest;

typedef boost::shared_ptr< ::localizer_dwm1001::Tag_srvRequest > Tag_srvRequestPtr;
typedef boost::shared_ptr< ::localizer_dwm1001::Tag_srvRequest const> Tag_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::localizer_dwm1001::Tag_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::localizer_dwm1001::Tag_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace localizer_dwm1001

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::localizer_dwm1001::Tag_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::localizer_dwm1001::Tag_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::localizer_dwm1001::Tag_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::localizer_dwm1001::Tag_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::localizer_dwm1001::Tag_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::localizer_dwm1001::Tag_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::localizer_dwm1001::Tag_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::localizer_dwm1001::Tag_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::localizer_dwm1001::Tag_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "localizer_dwm1001/Tag_srvRequest";
  }

  static const char* value(const ::localizer_dwm1001::Tag_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::localizer_dwm1001::Tag_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::localizer_dwm1001::Tag_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::localizer_dwm1001::Tag_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Tag_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::localizer_dwm1001::Tag_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::localizer_dwm1001::Tag_srvRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // LOCALIZER_DWM1001_MESSAGE_TAG_SRVREQUEST_H
