// Generated by gencpp from file localizer_dwm1001/Tag_srv.msg
// DO NOT EDIT!


#ifndef LOCALIZER_DWM1001_MESSAGE_TAG_SRV_H
#define LOCALIZER_DWM1001_MESSAGE_TAG_SRV_H

#include <ros/service_traits.h>


#include <localizer_dwm1001/Tag_srvRequest.h>
#include <localizer_dwm1001/Tag_srvResponse.h>


namespace localizer_dwm1001
{

struct Tag_srv
{

typedef Tag_srvRequest Request;
typedef Tag_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Tag_srv
} // namespace localizer_dwm1001


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::localizer_dwm1001::Tag_srv > {
  static const char* value()
  {
    return "4a842b65f413084dc2b10fb484ea7f17";
  }

  static const char* value(const ::localizer_dwm1001::Tag_srv&) { return value(); }
};

template<>
struct DataType< ::localizer_dwm1001::Tag_srv > {
  static const char* value()
  {
    return "localizer_dwm1001/Tag_srv";
  }

  static const char* value(const ::localizer_dwm1001::Tag_srv&) { return value(); }
};


// service_traits::MD5Sum< ::localizer_dwm1001::Tag_srvRequest> should match
// service_traits::MD5Sum< ::localizer_dwm1001::Tag_srv >
template<>
struct MD5Sum< ::localizer_dwm1001::Tag_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::localizer_dwm1001::Tag_srv >::value();
  }
  static const char* value(const ::localizer_dwm1001::Tag_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::localizer_dwm1001::Tag_srvRequest> should match
// service_traits::DataType< ::localizer_dwm1001::Tag_srv >
template<>
struct DataType< ::localizer_dwm1001::Tag_srvRequest>
{
  static const char* value()
  {
    return DataType< ::localizer_dwm1001::Tag_srv >::value();
  }
  static const char* value(const ::localizer_dwm1001::Tag_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::localizer_dwm1001::Tag_srvResponse> should match
// service_traits::MD5Sum< ::localizer_dwm1001::Tag_srv >
template<>
struct MD5Sum< ::localizer_dwm1001::Tag_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::localizer_dwm1001::Tag_srv >::value();
  }
  static const char* value(const ::localizer_dwm1001::Tag_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::localizer_dwm1001::Tag_srvResponse> should match
// service_traits::DataType< ::localizer_dwm1001::Tag_srv >
template<>
struct DataType< ::localizer_dwm1001::Tag_srvResponse>
{
  static const char* value()
  {
    return DataType< ::localizer_dwm1001::Tag_srv >::value();
  }
  static const char* value(const ::localizer_dwm1001::Tag_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LOCALIZER_DWM1001_MESSAGE_TAG_SRV_H
